[package]
name = "pulsync"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", default-features = false, features = ["rt", "time"] }
tracing = { version = "0.1.27", default-features = false }
